name: Linux build

on:
  workflow_dispatch:
  schedule:
    - cron: "30 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: |
          chmod +x ./linux_build.sh
          ./linux_build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: aseprite-linux
          path: github
          if-no-files-found: error

      - name: Upload AppImage
        uses: actions/upload-artifact@v7
        with:
          name: Aseprite.AppImage
          path: github/Aseprite.AppImage
          if-no-files-found: error
